---
- hosts: all
  become: yes
  tasks: 
  - name: connect all
    ping:
  tasks:
  - name: installtion of nginx
    apt:
      name: nginx
      state: present
  - name: start nginx
    service:
      name: nginx
      state: start
  